name: CD - Deploy Backend

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - backend/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: amigoscode
          POSTGRES_PASSWORD: password
          POSTGRES_DB: customer
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Send Hello Slack Message
        run: >
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Logging in to Docker"}' https://hooks.slack.com/services/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
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Docker message
        run: >
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Docker login successful!!! Moving to set build Number"}' https://hooks.slack.com/services/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
      - name: Set build number
        id: build-number
        run: echo "BUILD_NUMBER=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT
      - name: Build Number message
        run: >
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Maven build started!!!"}' https://hooks.slack.com/services/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
      - name: Build Package Push with Maven
        run: mvn -ntp -B verify -Ddocker.image.tag=${{steps.build-number.outputs.BUILD_NUMBER}} jib:build
      - name: Docker aws message
        run: >
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Maven build successful!!! Moving to update Docker aws file"}' https://hooks.slack.com/services/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
      - name: Update Dockerrun.aws.json
        run: |
          echo "Dockerrun.aws.json before updating tag"
          cat Dockerrun.aws.json
          sed -i -E 's_(manojoshi1982/customer-service:)([^"]*)_\1'${{steps.build-number.outputs.BUILD_NUMBER}}'_' Dockerrun.aws.json
          echo "Dockerrun.aws.json after updating tag"
          cat Dockerrun.aws.json
      - name: EBS message
        run: >
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Dcoker aws json update successful!!! Moving to EBS deployment"}' https://hooks.slack.com/services/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
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APPLICATION_NAME }}
          environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
          version_label: ${{ steps.build-number.outputs.BUILD_NUMBER }}
          version_description: ${{ github.SHA }}
          region: ${{ secrets.EB_REGION }}
          deployment_package: backend/Dockerrun.aws.json
      - name: Deployment done Message
        run: >
          curl -X POST -H 'Content-type: application/json' --data '{"text":"EBS deployment successful!!!"}' https://hooks.slack.com/services/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
      - name: Commit and push the Dockerrun.aws.json file
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update Dockerrun.aws.json docker image with new tag ${{ steps.build-number.outputs.BUILD_NUMBER }}"
          git push
